name=input("What is your name?: ")
print("Hello " + name+ "!")
weight=input("What is your weight in pounds?: ")
weight=float(weight)
height=input("What is your height in inches?: ")
height=float(height)
bmi=(weight/(height*height))*703
print("Your BMI is: " + str(bmi))
if bmi<18.5:print("You are a skinny and petite fella.")
if bmi>18.5 and bmi<25:print("You are the average fella.")
if bmi>25:print("You are a fat and big fella")